### PR TITLE
use `wqp pull` step to capture siteinfo, then add to remake steps

### PR DESCRIPTION
**Pull request by lindsaycarr**
I ran this for Alabama as a test, but want to get an opinion on how I did this before running it for more of them.

These are the files that now appear in `out/data/` for nitrate. In `tmp/data/`, there is also a `Alabama_nitrate_001_siteinfo.rds` file.

image

### CODE REVIEW

**Comment by aappling-usgs** [comment]
Cool! Looking at your code I think I see a relatively small modification you could make that would make this process a little more traceable. Posting an image here, and maybe we can discuss briefly during our call in 30 min.

img_20180705_153202298

A difference between past code iterations and this one would be that the first data product contains an object with both the sample data and the site data. I forget whether feather format permits complex structures, but RDS would also be fine there.

The second and third steps in each column (extract and post) could be merged together into a single step per column because the extraction likely to be quick and reliable, such that there's no big reason to separate it out or save a second near-identical copy of each data file.

**Comment by lindsaycarr** [comment]
@aappling-usgs wondering if I should commit the tmp/ directory and/or make the `gd_put` step part of the extract data and extract siteinfo steps? I can't remember if we do one, we don't need to do the other or not.

**Comment by lindsaycarr** [comment]
@aappling-usgs do you have time to review this soon?

**Comment by aappling-usgs** [comment]
Yes, this is one of four emails I still have as Unread = high priority coming out of my AL and travel and vizstorm weeks...I'll do my best. When are you hoping to resume work on this?

**Comment by lindsaycarr** [comment]
Ok, gotcha! No worries, just didn't want to forget about it. I was hoping to resume work this week since I think they were looking to have some more info by end of july

**Pull request merged**
